import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import CartProvider from "@/providers/CartProviders";
import Toaster from "react-hot-toast";
// import { getCurrentUser } from "@/actions/getCurrentUser";
// import { getCurrentUser } from "@/actions/getCurrentUser";
// import React, { useEffect, useState } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '700', '500']
});

export const metadata: Metadata = {
  title: "School-shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const currentUser = await getCurrentUser();

  // console.log()

  return (
    <html lang="en">
      <body className={`${poppins.className} text-slate-700`}>
        <Toaster toastOptions={{
          style: {
            background: "rgb(51 65 85)",
            color: "#fff",
          }
        }}
        />
        <CartProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
